
[title]
en = "Things I've made trying to put my dent in the universe."
de = ""

[intro]
en = [
    "I've worked on tons of little projects over the years but these are ",
    "the ones that I'm most proud of. Many of them are open-source, so if you see ",
    "something that piques your interest, check out the code and contribute if you ",
    "have ideas for how it can be improved.",
]
de = ""

[[projects]]

name = { en = "Planetaria", de = "" }
description = { en = "Creating technology to empower civilians to explore space on their own terms.", de = "" }
link = { href = "http://planetaria.tech", label = "planetaria.tech" }
logo = "/images/logos/planetaria.svg"
[[projects]]


name = { en = "Animaginary", de = "" }
description = { en = "High performance web animation library, hand-written in optimized WASM.", de = "" }
link = { href = "#", label = "github.com" }
logo = "/images/logos/animaginary.svg"
[[projects]]

name = { en = "HelioStream", de = "" }
description = { en = "Real-time video streaming library, optimized for interstellar transmission.", de = "" }
link = { href = "#", label = "github.com" }
logo = "/images/logos/helio-stream.svg"
[[projects]]

name = { en = "cosmOS", de = "" }
description = { en = "The operating system that powers our Planetaria space shuttles.", de = "" }
link = { href = "#", label = "github.com" }
logo = "/images/logos/cosmos.svg"
[[projects]]

name = { en = "OpenShuttle", de = "" }
description = { en = "The schematics for the first rocket I designed that successfully made it to orbit.", de = "" }
link = { href = "#", label = "github.com" }
logo = "/images/logos/open-shuttle.svg"
